### ISSUE TITLE
Doc for initial redis setup?

### ISSUE THREAD

**Issue by TobiTenno** [cubic-js/cubic#147]
There's no documentation about it, but the initial setup presented in README.md causes errors if you don't have a local Redis instance set up.

Might just need a mention that it is required. (Along with others that I'll list below as I find them)

- [ ] Redis
- [ ] MongoDB

**Comment by Kaptard** [comment]
Oof, sorry. It was actually part of the readme in an earlier version but somehow got out. Thanks for letting us know!

**Comment by TobiTenno** [comment]
Thanks a bunch!
